### PR TITLE
DO NOT MERGE ME

### PR DESCRIPTION
**Pull request by thejunglejane**
Testing out what check status will look like if a PR changes code coverage.

### CODE REVIEW

**Comment by thejunglejane** [comment]
Oh dammit I didn't mean to break Travis.

**Comment by thejunglejane** [comment]
OKay I don't know why Travis failed that time.

**Comment by leifwalsh** [comment]
Our tox config tries to combine data produced by test_main.py. Could you try just deleting a couple of tests, but not all of them?

**Comment by leifwalsh** [comment]
So, that's what that looks like.

**Comment by leifwalsh** [comment]
I'm ok with that if you are, as administrators we can still override it but it makes it obvious that coverage dropped.

**Pull request closed without merging**
